telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051c3ac8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051d5198>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051de4a8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051de5f8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051de6d8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051deb00>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051deba8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051ded68>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051de898>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051f72e8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051f7390>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051f7588>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=3 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051f7048>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051f7b00>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051def98>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051def60>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=4 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1051dec88>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10eab7a20>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10eab7f60>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10ead24a8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10ead25f8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=1 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10ead26d8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10ead2b38>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10ead2be0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10ead2da0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=2 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10ead28d0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10eaeb320>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10eaeb3c8>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10eaeb588>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=3 max_retries=-1
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10eaeb080>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10eaebb38>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.vendor.ptb_urllib3.urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10ead2fd0>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',)': /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook
telegram.ext.updater - ERROR - Error while bootstrap del webhook: urllib3 HTTPError SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot743204620:AAGgWtqwunxoLNaENb1ofdcFMIUQzBhHHko/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x10ead2f60>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset',))
telegram.ext.updater - WARNING - Failed bootstrap phase; try=4 max_retries=-1
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "../lesson1/bot_planet.py", line 55, in planet
    plan_time = getattr(ephem,plan)(right_date)
AttributeError: module 'ephem' has no attribute ''
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "../lesson1/bot_planet.py", line 55, in planet
    plan_time = getattr(ephem,plan)(right_date)
AttributeError: module 'ephem' has no attribute ''
telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "../lesson1/bot_planet.py", line 55, in planet
    plan_time = getattr(ephem,plan)(right_date)
AttributeError: module 'ephem' has no attribute ''
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
